rename MLOS in PML
ow2-proactive/documentation pull request #701
Opened 2021-03-12 21:51 UTC by MaelAudren

2021-03-15 09:44 UTC, Hiba-Alili requested changes

2021-03-15 09:44 UTC, Hiba-Alili commented on src/docs/index.adoc
> +=== Machine Learning Open Studio (PML)
Could you please update _Machine Learning Open Studio (PML)_ to _ProActive Machine Learning (PML)_

2021-03-15 09:44 UTC, Hiba-Alili commented on src/docs/index.adoc
> +* link:PML/PMLUserGuide.html[*PML User Guide*] (​a complete Data Science and Machine Learning Platform)
​a complete Data Science and Machine Learning Platform -> a complete Data Science and Machine Learning platform, with Studio & MLOps.

2021-03-15 09:44 UTC, Hiba-Alili commented on src/docs/all-doc-links.adoc
> +<h3 id="_machine_learning_open_studio_pml"><a class="anchor" href="#_machine_learning_open_studio_pml"></a><a class="link" href="#_machine_learning_open_studio_pml">ProActive Machine Learning (PML)</
I think that _#_machine_learning_open_studio_pml_ should be updated to _#_proactive_machine_learning_pml_

2021-03-16 13:08 UTC, mboussaa approved these changes

2021-03-17 10:49 UTC, Hiba-Alili approved these changes

2021-03-17 15:42 UTC, merged