Update PSA services documentation
ow2-proactive/documentation pull request #777
Opened 2021-12-15 12:44 UTC by medou-boushab

2021-12-16 10:20 UTC, mboussaa commented on src/docs/PSA/references/Service_Execution.adoc
> +2- Via Workflow Execution Portal. To launch PSA service, you have to open the Submit Template and choose PSA service from the selected bucket. At this point, you can provide values for variables that
2- Via Workflow Execution Portal. To launch PSA services, you have to open the Submit Window in the Workflow Execution Portal and then select 'Service Workflows Only' option to filter PSA services from the list of workflows. After selecting a PSA service to submit, you can provide variable values that help configure this service then press submit.

2021-12-16 10:21 UTC, mboussaa requested changes
some changes

2021-12-20 08:46 UTC, mboussaa commented on src/docs/PSA/references/Service_Execution.adoc
> +2- Via Workflow Execution Portal. To launch PSA services, you have to open the Submit Window in the Workflow Execution Portal and then select 'Service Workflows Only'
remove line break after Service Workflows Only

2021-12-20 08:46 UTC, mboussaa approved these changes

2021-12-20 08:59 UTC, aminelouati approved these changes

2021-12-21 09:07 UTC, mboussaa commented
restest this!

2021-12-21 09:09 UTC, merged